# Generated by Django 3.1.1 on 2020-09-30 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_normalizado', models.SlugField(max_length=255)),
            ],
            options={
                'verbose_name': 'continente',
                'verbose_name_plural': 'continentes',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ibge', models.IntegerField(blank=True, db_index=True)),
                ('nome', models.CharField(max_length=255)),
                ('nome_normalizado', models.SlugField(max_length=255)),
                ('sigla', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'estado',
                'verbose_name_plural': 'estados',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Fonte de Dados',
                'verbose_name_plural': 'Fontes de Dados',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ibge', models.IntegerField(blank=True, db_index=True)),
                ('nome', models.CharField(max_length=255)),
                ('nome_normalizado', models.SlugField(max_length=255)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.estado')),
            ],
            options={
                'verbose_name': 'município',
                'verbose_name_plural': 'municípios',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_normalizado', models.SlugField(max_length=255)),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.continente')),
            ],
            options={
                'verbose_name': 'país',
                'verbose_name_plural': 'países',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Variavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_normalizado', models.SlugField(max_length=255)),
                ('abrangencia', models.CharField(choices=[('CONT', 'Continente'), ('PAIS', 'Pais'), ('ESTA', 'Estado'), ('MUNI', 'Municipio')], max_length=4)),
                ('ativa', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('unidade', models.CharField(blank=True, choices=[('SEMU', 'Sem Unidade'), ('REAL', 'Moeda (Real)'), ('DOLA', 'Moeda (Dolar)'), ('EURO', 'Moeda (Euro)'), ('PORC', 'Porcentagem')], max_length=4)),
                ('fonte', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dados.fonte')),
            ],
            options={
                'verbose_name': 'variável',
                'verbose_name_plural': 'variáveis',
                'ordering': ('nome',),
            },
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.pais'),
        ),
        migrations.CreateModel(
            name='VariavelPaisInteiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.pais')),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.variavel')),
            ],
            options={
                'abstract': False,
                'unique_together': {('variavel', 'pais', 'data')},
            },
        ),
        migrations.CreateModel(
            name='VariavelPaisDecimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.pais')),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.variavel')),
            ],
            options={
                'abstract': False,
                'unique_together': {('variavel', 'pais', 'data')},
            },
        ),
        migrations.CreateModel(
            name='VariavelMunicipioInteiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.municipio')),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.variavel')),
            ],
            options={
                'abstract': False,
                'unique_together': {('variavel', 'municipio', 'data')},
            },
        ),
        migrations.CreateModel(
            name='VariavelMunicipioDecimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.municipio')),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.variavel')),
            ],
            options={
                'abstract': False,
                'unique_together': {('variavel', 'municipio', 'data')},
            },
        ),
        migrations.CreateModel(
            name='VariavelEstadoInteiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.estado')),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.variavel')),
            ],
            options={
                'abstract': False,
                'unique_together': {('variavel', 'estado', 'data')},
            },
        ),
        migrations.CreateModel(
            name='VariavelEstadoDecimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.estado')),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.variavel')),
            ],
            options={
                'abstract': False,
                'unique_together': {('variavel', 'estado', 'data')},
            },
        ),
        migrations.CreateModel(
            name='VariavelContinenteInteiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.continente')),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.variavel')),
            ],
            options={
                'abstract': False,
                'unique_together': {('variavel', 'continente', 'data')},
            },
        ),
        migrations.CreateModel(
            name='VariavelContinenteDecimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.continente')),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.variavel')),
            ],
            options={
                'abstract': False,
                'unique_together': {('variavel', 'continente', 'data')},
            },
        ),
    ]
