# Generated by Django 3.1.1 on 2020-09-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0002_auto_20200930_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='nome_normalizado',
            field=models.SlugField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nome_normalizado',
            field=models.SlugField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nome_normalizado',
            field=models.SlugField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='variavel',
            name='nome_normalizado',
            field=models.SlugField(editable=False, max_length=255),
        ),
    ]
