# Generated by Django 3.1.1 on 2020-10-07 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0003_auto_20200930_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grafico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nome_normalizado', models.SlugField(editable=False, max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('abrangencia', models.CharField(choices=[('CONT', 'Continente'), ('PAIS', 'Pais'), ('ESTA', 'Estado'), ('MUNI', 'Municipio')], max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='variavel',
            name='unidade',
            field=models.CharField(blank=True, choices=[('SEMU', 'Sem Unidade'), ('INTE', 'Inteiro'), ('DECI', 'Decimal'), ('REAL', 'Moeda (Real)'), ('DOLA', 'Moeda (Dolar)'), ('EURO', 'Moeda (Euro)'), ('PORC', 'Porcentagem')], max_length=4),
        ),
        migrations.CreateModel(
            name='OrdemVariaveisGrafico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=0)),
                ('grafico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.grafico')),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.variavel')),
            ],
        ),
        migrations.AddField(
            model_name='grafico',
            name='variaveis',
            field=models.ManyToManyField(related_name='variaveis_do_grafico', through='dados.OrdemVariaveisGrafico', to='dados.Variavel'),
        ),
    ]
