# Generated by Django 3.1.1 on 2020-10-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0005_auto_20201007_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grafico',
            options={'ordering': ('nome',), 'verbose_name': 'Gráfico', 'verbose_name_plural': 'Gráficos'},
        ),
        migrations.AlterModelOptions(
            name='variaveisgrafico',
            options={'verbose_name': 'variável do gráfico', 'verbose_name_plural': 'variáveis do gráfico'},
        ),
        migrations.AddField(
            model_name='grafico',
            name='tipo',
            field=models.CharField(blank=True, choices=[('LINH', 'Linhas'), ('BARR', 'Barras')], max_length=4),
        ),
        migrations.AlterField(
            model_name='grafico',
            name='abrangencia',
            field=models.CharField(choices=[('CONT', 'Continente'), ('PAIS', 'País'), ('ESTA', 'Estado'), ('MUNI', 'Município')], max_length=4),
        ),
        migrations.AlterField(
            model_name='variavel',
            name='abrangencia',
            field=models.CharField(choices=[('CONT', 'Continente'), ('PAIS', 'País'), ('ESTA', 'Estado'), ('MUNI', 'Município')], max_length=4),
        ),
    ]
