# Generated by Django 3.1.1 on 2020-10-07 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0006_auto_20201007_1630'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variaveisgrafico',
            unique_together={('grafico', 'variavel')},
        ),
    ]
