# Generated by Django 3.1.1 on 2020-10-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0007_auto_20201007_1720'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variavelcontinentedecimal',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='variavelcontinenteinteiro',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='variavelestadodecimal',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='variavelestadointeiro',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='variavelmunicipiodecimal',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='variavelmunicipiointeiro',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='variavelpaisdecimal',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='variavelpaisinteiro',
            unique_together=set(),
        ),
    ]
