# Generated by Django 3.1.1 on 2020-10-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0009_auto_20201021_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variavelcontinentedecimal',
            old_name='valora',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='variavelcontinenteinteiro',
            old_name='valora',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='variavelestadodecimal',
            old_name='valora',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='variavelestadointeiro',
            old_name='valora',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='variavelmunicipiodecimal',
            old_name='valora',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='variavelmunicipiointeiro',
            old_name='valora',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='variavelpaisdecimal',
            old_name='valora',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='variavelpaisinteiro',
            old_name='valora',
            new_name='valor',
        ),
    ]
