# Generated by Django 3.1.1 on 2020-10-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0010_auto_20201021_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variavelcontinentedecimal',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='variavelcontinenteinteiro',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='variavelestadodecimal',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='variavelestadointeiro',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='variavelmunicipiodecimal',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='variavelmunicipiointeiro',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='variavelpaisdecimal',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='variavelpaisinteiro',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
