# Generated by Django 3.1.1 on 2020-11-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0012_auto_20201103_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='codigo_ibge',
            field=models.IntegerField(db_index=True),
        ),
    ]
