# Generated by Django 3.1.1 on 2020-11-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0013_auto_20201103_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='numero_habitantes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variavel',
            name='variavel_exclusiva_do_estado_RS',
            field=models.BooleanField(default=False),
        ),
    ]
