# Generated by Django 3.1.1 on 2020-11-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0015_auto_20201104_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='total_de_repasse_programa_apoio_financeiro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
    ]
