# Generated by Django 3.1.1 on 2020-11-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0016_municipio_total_de_repasse_programa_apoio_financeiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('instituicao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instituição')),
                ('equipe', models.CharField(choices=[('COOR', 'Coordenação'), ('EXEC', 'Equipe Executiva'), ('OPER', 'Equipe Operacional'), ('APOI', 'Estrutura Apoiadora'), ('COLA', 'Equipe Colaborativa'), ('FINA', 'Estrutura Financiadora')], max_length=4)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Integrante',
                'verbose_name_plural': 'Integrantes',
                'ordering': ('ordem', 'nome'),
            },
        ),
    ]
