# Generated by Django 3.1.1 on 2020-12-02 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0017_integrante'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextoOficial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('data', models.DateField(db_index=True)),
                ('descricao', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Descrição')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dados.estado')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dados.pais')),
            ],
            options={
                'verbose_name': 'Texto Oficial',
                'verbose_name_plural': 'Textos Oficiais',
                'ordering': ('-data',),
            },
        ),
    ]
