# Generated by Django 3.1.1 on 2020-12-08 17:51

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0019_textooficial_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dados.integrante')),
            ],
            options={
                'verbose_name': 'autor do documento',
                'verbose_name_plural': 'autores do documento',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('data', models.DateField(db_index=True)),
                ('tipo', models.CharField(blank=True, choices=[('CONJ', 'Análise de Conjuntura'), ('DISC', 'Texto para Discussão')], max_length=4)),
                ('arquivo', easy_thumbnails.fields.ThumbnailerField(upload_to='documents/%Y/%m/%d/')),
                ('autores', models.ManyToManyField(related_name='autores_do_documento', through='dados.AutorDocumento', to='dados.Integrante')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ('-data',),
            },
        ),
        migrations.AddField(
            model_name='autordocumento',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dados.documento'),
        ),
        migrations.AlterUniqueTogether(
            name='autordocumento',
            unique_together={('documento', 'autor')},
        ),
    ]
