# Generated by Django 3.1.1 on 2020-12-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0020_auto_20201208_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autordocumento',
            options={'ordering': ('ordem',), 'verbose_name': 'autor do documento', 'verbose_name_plural': 'autores do documento'},
        ),
        migrations.AlterModelOptions(
            name='integrante',
            options={'ordering': ('nome', 'ordem'), 'verbose_name': 'Integrante', 'verbose_name_plural': 'Integrantes'},
        ),
        migrations.AddField(
            model_name='documento',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
