# Generated by Django 3.1.1 on 2020-12-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0021_auto_20201209_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='numero',
            field=models.IntegerField(default=0, verbose_name='Número'),
        ),
    ]
