# Generated by Django 3.1.1 on 2020-12-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0022_auto_20201209_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiaExterna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=1000, verbose_name='Título')),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('fonte', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Notícia Externa',
                'verbose_name_plural': 'Notícias Externas',
                'ordering': ('-id',),
            },
        ),
    ]
