# Generated by Django 3.1.1 on 2020-12-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0023_noticiaexterna'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiaexterna',
            name='tipo',
            field=models.CharField(blank=True, choices=[('CRIA', 'Criação'), ('NOTI', 'Notícia de Opinião e Entrevistas'), ('LIVE', 'Lives')], max_length=4),
        ),
    ]
